# Test the SeleniumBase Python package with Azure Pipelines.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python setup.py develop
    displayName: 'Install SeleniumBase'

  - script: |
      sudo apt install google-chrome-stable
      sudo apt-get install firefox
    displayName: 'Install Chrome and Firefox'

  - script: |
      seleniumbase install chromedriver
      seleniumbase install geckodriver
    displayName: 'Install chromedriver and geckodriver (Firefox Webdriver)'

  - script: |
      echo "def test_1(): pass" > nothing.py
      pytest nothing.py
    displayName: 'Make sure pytest is working'

  - script: pytest examples/boilerplates/boilerplate_test.py --browser=chrome --headless -v -s --junitxml=junit/test-results.xml
    displayName: 'Run pytest boilerplate_test.py --browser=chrome --headless'

  - script: pytest examples/my_first_test.py --browser=chrome --headless -v -s --junitxml=junit/test-results.xml
    displayName: 'Run pytest my_first_test.py --browser=chrome --headless'

  - script: pytest examples/my_first_test.py --browser=firefox --headless -v -s --junitxml=junit/test-results.xml
    displayName: 'Run pytest my_first_test.py --browser=firefox --headless'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: 'Publish'
  dependsOn: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: python setup.py sdist
    displayName: 'Build sdist'
